import { useState } from 'react';
import { useStore } from '../store/useStore';
import { motion } from 'framer-motion';
import { 
  FileText, Clipboard, Send, 
  Clock, CheckCircle2, AlertTriangle, MessageSquare
} from 'lucide-react';

export default function ShiftBrief() {
  const { patients, alerts, addToast } = useStore();
  const [selectedPatientId, setSelectedPatientId] = useState(patients[0]?.patient_id || '');

  const selectedPatient = patients.find(p => p.patient_id === selectedPatientId);
  const patientAlerts = alerts.filter(a => a.patientId === selectedPatientId);

  const generateSBAR = () => {
    if (!selectedPatient) return null;

    return {
      situation: `Patient ${selectedPatient.name} is currently in the ${selectedPatient.risk_tier} risk tier with a crash probability of ${Math.round(selectedPatient.crash_probability * 100)}%.`,
      background: `Admitted for ${selectedPatient.diagnosis}. Currently Day ${Math.floor((Date.now() - new Date(selectedPatient.admission_time).getTime()) / (1000 * 3600 * 24))} in ICU. Baseline hemodynamics show ${selectedPatient.vitals?.[0]?.heart_rate} bpm and ${selectedPatient.vitals?.[0]?.map_pressure} mmHg.`,
      assessment: `AI Model (Chronos-LSTM) has identified ${selectedPatient.top_drivers?.length || 0} acute risk drivers. Primary concern is ${selectedPatient.top_drivers?.[0]?.label || 'unspecified trend'}. Total of ${patientAlerts.length} system alerts generated in last 12 hours.`,
      recommendation: selectedPatient.counterfactual?.[0]?.action || "Continue close monitoring of vitals. Re-assess hemodynamics in 1 hour."
    };
  };

  const sbar = generateSBAR();

  const handleExport = () => {
    if (!sbar || !selectedPatient) return;
    
    const content = `
PROJECT CHRONOS - CLINICAL BRIEF
===============================
Patient: ${selectedPatient.name} (${selectedPatient.bed_id})
Date: ${new Date().toLocaleString()}

[S] SITUATION
${sbar.situation}

[B] BACKGROUND
${sbar.background}

[A] ASSESSMENT
${sbar.assessment}

[R] RECOMMENDATION
${sbar.recommendation}

-------------------------------
Generated by Chronos Clinical OS
    `.trim();

    const element = document.createElement("a");
    const file = new Blob([content], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `SBAR_${selectedPatient.bed_id}_${selectedPatient.name.replace(' ', '_')}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    
    addToast({ type: 'success', message: 'Clinical brief exported successfully.' });
  };

  const handleSend = () => {
    if (!selectedPatient) return;
    
    // Simulate API delay
    setTimeout(() => {
      addToast({ 
        type: 'success', 
        message: `SBAR Handover for ${selectedPatient.bed_id} transmitted to next shift.` 
      });
    }, 800);
  };

  return (
    <motion.div 
      initial={{ opacity: 0 }} 
      animate={{ opacity: 1 }}
      className="h-full flex flex-col mesh-gradient-bg p-8 gap-8 overflow-hidden"
    >
      <header className="shrink-0">
        <div className="flex items-center gap-3 mb-2">
          <div className="p-2 bg-emerald-500/20 rounded-lg">
            <Clipboard className="text-emerald-400" size={24} />
          </div>
          <h2 className="text-4xl font-extrabold text-white tracking-tight">Shift Handover</h2>
        </div>
        <p className="text-gray-400 font-medium ml-12 italic">Automated SBAR Generation for Clinical Continuity</p>
      </header>

      <div className="flex-1 flex gap-8 overflow-hidden">
        {/* PATIENT SELECTOR */}
        <div className="w-80 flex flex-col gap-4 overflow-y-auto pr-2 custom-scrollbar shrink-0">
          <h3 className="text-[10px] font-bold text-gray-500 uppercase tracking-[0.2em] mb-2">Select Patient</h3>
          {patients.map(p => (
            <button
              key={p.patient_id}
              onClick={() => setSelectedPatientId(p.patient_id)}
              className={`p-4 rounded-2xl border transition-all text-left flex items-center justify-between group ${
                selectedPatientId === p.patient_id
                ? 'bg-blue-600/20 border-blue-500/50 shadow-lg'
                : 'bg-white/5 border-white/10 hover:border-white/20'
              }`}
            >
              <div>
                <p className={`font-bold text-sm ${selectedPatientId === p.patient_id ? 'text-blue-400' : 'text-white'}`}>{p.name}</p>
                <p className="text-[10px] text-gray-500 mt-1">{p.bed_id}</p>
              </div>
              <div className={`w-2 h-2 rounded-full ${
                p.risk_tier === 'CRITICAL' ? 'bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.5)]' :
                p.risk_tier === 'HIGH' ? 'bg-orange-500' :
                p.risk_tier === 'WATCH' ? 'bg-yellow-500' : 'bg-emerald-500'
              }`}></div>
            </button>
          ))}
        </div>

        {/* SBAR CONTENT */}
        <div className="flex-1 flex flex-col gap-6 overflow-y-auto pr-2 custom-scrollbar">
          {sbar ? (
            <>
              <div className="grid grid-cols-2 gap-6">
                <SBARCard icon={AlertTriangle} title="Situation" content={sbar.situation} color="text-red-400" bg="bg-red-400/10" />
                <SBARCard icon={Clock} title="Background" content={sbar.background} color="text-blue-400" bg="bg-blue-400/10" />
              </div>
              <SBARCard icon={MessageSquare} title="Assessment (AI Reasoning)" content={sbar.assessment} color="text-yellow-400" bg="bg-yellow-400/10" />
              <SBARCard icon={CheckCircle2} title="Recommendation" content={sbar.recommendation} color="text-emerald-400" bg="bg-emerald-400/10" />

              <div className="mt-4 flex gap-4 shrink-0">
                <button 
                  onClick={handleExport}
                  className="flex-1 py-4 bg-white/5 hover:bg-white/10 rounded-2xl border border-white/10 text-white font-bold transition-all flex items-center justify-center gap-2"
                >
                  <FileText size={18} /> Export Brief
                </button>
                <button 
                  onClick={handleSend}
                  className="flex-1 py-4 bg-blue-600 hover:bg-blue-500 rounded-2xl text-white font-bold transition-all flex items-center justify-center gap-2 shadow-xl shadow-blue-900/20"
                >
                  <Send size={18} /> Send to Next Shift
                </button>
              </div>
            </>
          ) : (
            <div className="flex-1 flex items-center justify-center text-gray-600 italic">
               Select a patient bed from the sidebar to generate the clinical handover brief.
            </div>
          )}
        </div>
      </div>
    </motion.div>
  );
}

function SBARCard({ title, content, icon: Icon, color, bg }: any) {
  return (
    <div className="glass-card p-6 border border-white/5 flex gap-6">
      <div className={`shrink-0 w-12 h-12 rounded-xl flex items-center justify-center ${bg} ${color}`}>
        <Icon size={24} />
      </div>
      <div>
        <h4 className={`text-[10px] font-black uppercase tracking-[0.2em] mb-2 ${color}`}>{title}</h4>
        <p className="text-sm text-gray-300 leading-relaxed font-medium">{content}</p>
      </div>
    </div>
  );
}
